const db = window.supabase.createClient('https://fzdtkmixmodttroesjgn.supabase.co', 'sb_publishable_EjZt9V2__QZmOzLfYa-Czw_T_CRsDwR');
const state = { players: [], games: [], grounds: [], register: {}, club: null, profile: null, members: [], accessRoles: {} };
let selectedDate = '', editingPlayerId = '', playerSearchQuery = '';
let calendarMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1);
const expandedPlayers = new Set();
const $ = (selector) => document.querySelector(selector);
const dateInput = $('#selected-date'), groundInput = $('#selected-ground');
const squadLimit = 12;
const escapeHtml = (value) => { const node = document.createElement('div'); node.textContent = value || ''; return node.innerHTML; };
const formatDate = (value) => new Intl.DateTimeFormat('en-AU', { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${value}T12:00:00`));
const formatCurrency = (value) => new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD' }).format(Number(value) || 0);
const todayKey = () => new Date().toISOString().slice(0, 10);
const currentGame = () => state.games.find((game) => game.date === selectedDate);
const isAmount = (value) => value !== null && value !== undefined && value !== '' && Number.isFinite(Number(value));
const role = () => state.profile?.role || '';
const canManage = () => ['admin', 'manager'].includes(role());
const canCaptain = () => canManage() || role() === 'captain';
const isPast = (date = selectedDate) => Boolean(date && date < todayKey());
const canEditField = (field, playerId) => canManage() || (!isPast() && ((field === 'selected' && canCaptain()) || (field === 'registered' && role() === 'player' && playerId === state.profile?.player_id)));
const setVisible = (selector, visible) => { $(selector).hidden = !visible; };

async function loadData() {
  const profile = await db.from('profiles').select('*').eq('user_id', (await db.auth.getUser()).data.user.id).single();
  if (profile.error || !profile.data) return showAuthMessage('Your account is still being set up. Refresh in a moment.');
  state.profile = profile.data;
  const requests = [db.from('players').select('*').order('name'), db.from('games').select('*').order('game_date'), db.from('grounds').select('*').order('is_home', { ascending: false }).order('name'), db.from('registrations').select('*'), db.from('club_settings').select('*').eq('id', true).single()];
  if (role() === 'admin') { requests.push(db.from('profiles').select('user_id,role,player_id,players(name,email)').order('created_at')); requests.push(db.from('player_access_roles').select('*')); }
  const [players, games, grounds, registrations, club, members, accessRoles] = await Promise.all(requests);
  const error = players.error || games.error || grounds.error || registrations.error || club.error || members?.error || accessRoles?.error;
  if (error) { console.error(error); $('#roster-caption').textContent = 'Could not load the shared register. Refresh and try again.'; return; }
  state.players = players.data || []; state.grounds = grounds.data || []; state.club = club.data;
  state.games = (games.data || []).map((game) => ({ date: game.game_date, ground_id: game.ground_id })); state.members = members?.data || []; state.accessRoles = Object.fromEntries((accessRoles?.data || []).map((entry) => [entry.player_id, entry.role]));
  state.register = {}; (registrations.data || []).forEach((record) => { state.register[record.game_date] ||= {}; state.register[record.game_date][record.player_id] = { registered: !!record.registered, selected: !!record.selected, attended: !!record.attended, paid: !!record.paid, amount: record.amount }; });
  render();
}

function render() {
  $('#player-count').textContent = state.players.length;
  $('#account-role').textContent = role();
  $('#account-email').textContent = state.currentEmail || '';
  setVisible('#add-game', canManage()); setVisible('#delete-game', canManage()); setVisible('#add-player-roster', canManage()); setVisible('#add-player-list', canManage()); setVisible('#export-data', canManage()); setVisible('#members-tab', role() === 'admin'); setVisible('#edit-club', canManage());
  const selectedGround = groundInput.value; groundInput.innerHTML = state.grounds.map((ground) => `<option value="${ground.id}">${escapeHtml(ground.name)}${ground.is_home ? ' (Home Ground)' : ''}</option>`).join('');
  groundInput.value = state.grounds.some((ground) => ground.id === selectedGround) ? selectedGround : (state.grounds.find((ground) => ground.is_home)?.id || state.grounds[0]?.id || ''); dateInput.value = selectedDate;
  const game = currentGame(), ground = state.grounds.find((item) => item.id === game?.ground_id);
  $('#selected-date-label').textContent = selectedDate ? formatDate(selectedDate) : 'Choose a day on the calendar'; $('#game-status').textContent = game ? `${formatDate(game.date)} — ${ground?.name || 'Ground not set'}` : 'Choose a date'; $('#delete-game').disabled = !game;
  if (state.club) { $('#club-name').textContent = state.club.name; $('#hero-club-name').textContent = state.club.name; $('#club-description').textContent = state.club.description; $('#hero-description').textContent = state.club.description; $('#club-fee').textContent = formatCurrency(state.club.game_fee); $('#club-banking').innerHTML = `BSB: ${escapeHtml(state.club.bsb)}<br>Account number: ${escapeHtml(state.club.account_number)}`; }
  renderCalendar(); renderSummary(); renderRoster(); renderPlayers(); renderMembers();
}

function renderCalendar() {
  const year = calendarMonth.getFullYear(), month = calendarMonth.getMonth(), firstWeekday = (new Date(year, month, 1).getDay() + 6) % 7, days = new Date(year, month + 1, 0).getDate(), today = todayKey();
  $('#calendar-month').textContent = new Intl.DateTimeFormat('en-AU', { month: 'long', year: 'numeric' }).format(calendarMonth);
  const scheduled = new Map(state.games.map((game) => [game.date, state.grounds.find((ground) => ground.id === game.ground_id)]));
  $('#calendar-days').innerHTML = Array.from({ length: firstWeekday }, () => '<span class="calendar-blank"></span>').concat(Array.from({ length: days }, (_, i) => { const date = `${year}-${String(month + 1).padStart(2, '0')}-${String(i + 1).padStart(2, '0')}`, ground = scheduled.get(date), classes = ['calendar-day', date < today ? 'is-past' : '', ground ? 'is-scheduled' : '', date === selectedDate ? 'is-selected' : '', date === today ? 'is-today' : ''].filter(Boolean).join(' '); return `<button type="button" class="${classes}" data-calendar-date="${date}" aria-label="${formatDate(date)}${ground ? `, scheduled at ${ground.name}` : ''}"><span class="calendar-day-number">${i + 1}</span>${ground ? `<span class="calendar-ground">${escapeHtml(ground.name)}</span>` : ''}</button>`; })).join('');
}

function renderSummary() { const records = selectedDate ? Object.values(state.register[selectedDate] || {}) : [], metrics = [['Available', records.filter((r) => r.registered).length], ['Selected', records.filter((r) => r.selected).length], ['Attended', records.filter((r) => r.attended).length], ['Paid', records.filter((r) => r.paid).length], ['Collected', formatCurrency(records.reduce((n, r) => n + (Number(r.amount) || 0), 0))]]; $('#game-summary').innerHTML = metrics.map(([label, value]) => `<div class="summary-item"><span>${label}</span><strong>${value}</strong></div>`).join(''); }

function renderRoster() {
  const roster = $('#roster'), records = state.register[selectedDate] || {}, selectedPlayerIds = new Set(Object.entries(records).filter(([, r]) => r.selected).map(([id]) => id)), squadIsFull = selectedPlayerIds.size >= squadLimit;
  $('#roster-caption').textContent = selectedDate ? (isPast() ? `${formatDate(selectedDate)} — historical register.` : `${formatDate(selectedDate)} — availability and selection are open.`) : 'Select a game date to view the register.';
  if (squadIsFull) $('#roster-caption').textContent += ` Squad of ${squadLimit} selected — unselected players are hidden.`;
  if (!selectedDate) { roster.innerHTML = '<div class="empty-state"><strong>Choose a game date first.</strong></div>'; return; }
  let players = isPast() ? state.players.filter((p) => { const r = records[p.id] || {}; return r.registered || r.selected || r.attended || r.paid || isAmount(r.amount); }) : state.players;
  if (squadIsFull) players = players.filter((p) => selectedPlayerIds.has(p.id));
  roster.innerHTML = players.map((player) => { const record = records[player.id] || {}, contact = [player.phone, player.email].filter(Boolean).join(' · '), amount = isAmount(record.amount) ? Number(record.amount).toFixed(2) : '', checkbox = (field, label, checked) => `<label class="check-label ${field}"><input type="checkbox" data-player="${player.id}" data-field="${field}" ${checked ? 'checked' : ''} ${canEditField(field, player.id) ? '' : 'disabled'}> ${label}</label>`; return `<div class="roster-row"><div class="player-info"><div class="player-name">${escapeHtml(player.name)}</div>${contact ? `<div class="player-contact">${escapeHtml(contact)}</div>` : ''}</div>${checkbox('registered', 'Available', record.registered)}${checkbox('selected', 'Selected', record.selected)}${checkbox('attended', 'Attended', record.attended)}${checkbox('paid', 'Paid', record.paid)}<label class="amount-label"><span>$</span><input type="number" min="0" step="0.01" data-player="${player.id}" data-field="amount" value="${amount}" ${canManage() ? '' : 'disabled'}></label></div>`; }).join('') || '<div class="empty-state"><strong>No player activity recorded for this date.</strong></div>';
}

function renderPlayers() {
  const list = $('#players-list'), players = state.players.filter((p) => p.name.toLocaleLowerCase().includes(playerSearchQuery));
  list.innerHTML = players.map((player) => { const history = state.games.map((game) => ({ date: game.date, ...(state.register[game.date]?.[player.id] || {}) })).filter((r) => r.registered || r.selected || r.attended || r.paid || isAmount(r.amount)), totals = { registered: history.filter((r) => r.registered).length, selected: history.filter((r) => r.selected).length, attended: history.filter((r) => r.attended).length, paid: history.filter((r) => r.paid).length, amount: history.reduce((n, r) => n + (Number(r.amount) || 0), 0) }, expanded = expandedPlayers.has(player.id), contact = [player.phone, player.email].filter(Boolean).join(' · ') || 'No contact details', rows = history.length ? history.sort((a, b) => b.date.localeCompare(a.date)).map((r) => `<li><span>${formatDate(r.date)}</span><span>${r.registered ? 'Available' : 'Not available'}</span><span>${r.selected ? 'Selected' : 'Not selected'}</span><span>${r.attended ? 'Attended' : 'Not attended'}</span></li>`).join('') : '<li class="payment-empty">No game records yet.</li>', controls = canManage() ? `<button class="text-button" type="button" data-edit-player="${player.id}">Edit</button><button class="button button-danger" type="button" data-delete-player="${player.id}">Remove</button>` : '', stat = (label, value) => `<div class="player-summary-stat"><span>${label}</span><strong>${value}</strong></div>`; return `<article class="player-card"><div class="player-card-main"><div><h3>${escapeHtml(player.name)}</h3><p>${escapeHtml(contact)}</p></div><div class="player-actions"><button class="text-button" type="button" data-toggle-player="${player.id}" aria-expanded="${expanded}">${expanded ? 'Hide summary' : 'View summary'}</button>${controls}</div></div><div class="player-payment-summary">${stat('Available', totals.registered)}${stat('Selected', totals.selected)}${stat('Attended', totals.attended)}${stat('Paid dates', totals.paid)}${stat('Total paid', formatCurrency(totals.amount))}</div>${expanded ? `<div class="player-history"><h4>Dates and payments</h4><ul>${rows}</ul></div>` : ''}</article>`; }).join('') || '<div class="empty-state"><strong>No matching players.</strong></div>';
}

function renderMembers() { if (role() !== 'admin') return; $('#members-list').innerHTML = state.members.map((member) => `<article class="player-card"><div class="player-card-main"><div><h3>${escapeHtml(member.players?.name || 'Unlinked user')}</h3><p>${escapeHtml(member.players?.email || '')}</p></div><label>Authority <select data-member-role="${member.user_id}">${['admin', 'manager', 'captain', 'player'].map((r) => `<option value="${r}" ${r === member.role ? 'selected' : ''}>${r[0].toUpperCase() + r.slice(1)}</option>`).join('')}</select></label></div></article>`).join('') || '<div class="empty-state"><strong>No members have registered yet.</strong></div>'; }

function openGameDialog(date = selectedDate) { dateInput.value = date || ''; $('#game-dialog').showModal(); dateInput.focus(); }
function openPlayerDialog(player) { editingPlayerId = player?.id || ''; $('#player-form').reset(); $('#player-dialog-title').textContent = editingPlayerId ? 'Edit player' : 'Add player'; $('#save-player').textContent = editingPlayerId ? 'Save changes' : 'Save player'; $('#player-name').value = player?.name || ''; $('#player-phone').value = player?.phone || ''; $('#player-email').value = player?.email || ''; $('#player-role-row').hidden = role() !== 'admin'; $('#player-role').value = state.accessRoles[player?.id] || 'player'; $('#player-dialog').showModal(); }
function openGroundDialog() { $('#ground-form').reset(); $('#ground-dialog').showModal(); }
function openClubDialog() { const c = state.club; $('#club-name-input').value = c.name; $('#club-description-input').value = c.description; $('#club-fee-input').value = c.game_fee; $('#club-bsb-input').value = c.bsb; $('#club-account-input').value = c.account_number; $('#club-dialog').showModal(); }
async function addGame() { const date = dateInput.value; if (!date) return; const { error } = await db.from('games').upsert({ game_date: date, ground_id: groundInput.value || null }); if (error) return alert(error.message); selectedDate = date; $('#game-dialog').close(); await loadData(); }
async function savePlayer() { const player = { name: $('#player-name').value.trim(), phone: $('#player-phone').value.trim(), email: $('#player-email').value.trim() }; if (!player.name) return; const request = editingPlayerId ? db.from('players').update(player).eq('id', editingPlayerId).select().single() : db.from('players').insert(player).select().single(); const { data, error } = await request; if (error) return alert(error.message); if (role() === 'admin') { const accessRole = $('#player-role').value; const planned = await db.from('player_access_roles').upsert({ player_id: data.id, role: accessRole }); if (planned.error) return alert(planned.error.message); const active = await db.from('profiles').update({ role: accessRole }).eq('player_id', data.id); if (active.error) return alert(active.error.message); } $('#player-dialog').close(); await loadData(); }
async function addGround() { const name = $('#ground-name').value.trim(); if (!name) return; if ($('#ground-home').checked) await db.from('grounds').update({ is_home: false }).eq('is_home', true); const { data, error } = await db.from('grounds').upsert({ name, is_home: $('#ground-home').checked }, { onConflict: 'name' }).select().single(); if (error) return alert(error.message); $('#ground-dialog').close(); await loadData(); groundInput.value = data.id; }
async function saveClub() { const update = { name: $('#club-name-input').value.trim(), description: $('#club-description-input').value.trim(), game_fee: Number($('#club-fee-input').value), bsb: $('#club-bsb-input').value.trim(), account_number: $('#club-account-input').value.trim(), updated_at: new Date().toISOString() }; const { error } = await db.from('club_settings').update(update).eq('id', true); if (error) return alert(error.message); $('#club-dialog').close(); await loadData(); }
async function saveRoster(input) { if (!selectedDate) return; const field = input.dataset.field, playerId = input.dataset.player, value = input.type === 'checkbox' ? input.checked : (input.value === '' ? null : Number(input.value).toFixed(2)); if (!canEditField(field, playerId)) return;
  if (role() === 'player') { const { error } = await db.rpc('set_my_availability', { p_game_date: selectedDate, p_available: value }); if (error) return alert(error.message); return loadData(); }
  if (role() === 'captain') { const { error } = await db.rpc('set_player_selected', { p_game_date: selectedDate, p_player_id: playerId, p_selected: value }); if (error) return alert(error.message); return loadData(); }
  const old = state.register[selectedDate]?.[playerId] || { registered: false, selected: false, attended: false, paid: false, amount: null }; if (field === 'selected' && value && !old.selected && Object.values(state.register[selectedDate] || {}).filter((r) => r.selected).length >= squadLimit) return alert(`Only ${squadLimit} players can be selected for a game.`); const update = { ...old, [field]: value }; const { error } = await db.from('registrations').upsert({ game_date: selectedDate, player_id: playerId, ...update }); if (error) return alert(error.message); await loadData();
}
function showAuthMessage(message) { $('#auth-message').textContent = message || ''; }
async function submitAuth(event) { event.preventDefault(); const email = $('#auth-email').value.trim(), password = $('#auth-password').value; let result; if ($('#auth-mode').value === 'signup') result = await db.auth.signUp({ email, password }); else result = await db.auth.signInWithPassword({ email, password }); if (result.error) return showAuthMessage(result.error.message); showAuthMessage($('#auth-mode').value === 'signup' ? 'Registration received. Check your email to confirm your account, then sign in.' : ''); }
async function startApp() { const { data: { session } } = await db.auth.getSession(); if (!session) { $('#auth-dialog').showModal(); return; } state.currentEmail = session.user.email; if ($('#auth-dialog').open) $('#auth-dialog').close(); await loadData(); }

document.querySelectorAll('[id^="add-player"]').forEach((b) => b.addEventListener('click', openPlayerDialog)); $('#player-search').addEventListener('input', (e) => { playerSearchQuery = e.target.value.trim().toLocaleLowerCase(); renderPlayers(); });
$('#add-ground').addEventListener('click', openGroundDialog); $('#ground-form').addEventListener('submit', (e) => { e.preventDefault(); addGround(); }); $('#player-form').addEventListener('submit', (e) => { e.preventDefault(); savePlayer(); }); $('#game-form').addEventListener('submit', (e) => { e.preventDefault(); addGame(); }); $('#club-form').addEventListener('submit', (e) => { e.preventDefault(); saveClub(); }); $('#edit-club').addEventListener('click', openClubDialog);
$('#add-game').addEventListener('click', () => openGameDialog()); $('#delete-game').addEventListener('click', async () => { if (!selectedDate || !confirm(`Delete ${formatDate(selectedDate)}?`)) return; const { error } = await db.from('games').delete().eq('game_date', selectedDate); if (error) return alert(error.message); selectedDate = ''; loadData(); });
$('#previous-month').addEventListener('click', () => { calendarMonth.setMonth(calendarMonth.getMonth() - 1); renderCalendar(); }); $('#next-month').addEventListener('click', () => { calendarMonth.setMonth(calendarMonth.getMonth() + 1); renderCalendar(); }); $('#calendar-days').addEventListener('click', (e) => { const b = e.target.closest('[data-calendar-date]'); if (!b) return; selectedDate = b.dataset.calendarDate; currentGame() ? render() : (canManage() ? openGameDialog(selectedDate) : render()); }); $('#roster').addEventListener('change', (e) => { if (e.target.matches('input[data-player]')) saveRoster(e.target); });
$('#players-list').addEventListener('click', async (e) => { const summary = e.target.closest('[data-toggle-player]'); if (summary) { const id = summary.dataset.togglePlayer; expandedPlayers.has(id) ? expandedPlayers.delete(id) : expandedPlayers.add(id); return renderPlayers(); } const edit = e.target.closest('[data-edit-player]'); if (edit) return openPlayerDialog(state.players.find((p) => p.id === edit.dataset.editPlayer)); const id = e.target.dataset.deletePlayer; if (!id || !confirm('Remove this player and their historical records?')) return; const { error } = await db.from('players').delete().eq('id', id); if (error) return alert(error.message); loadData(); });
$('#members-list').addEventListener('change', async (e) => { const id = e.target.dataset.memberRole; if (!id) return; const { error } = await db.from('profiles').update({ role: e.target.value }).eq('user_id', id); if (error) return alert(error.message); loadData(); });
$('#auth-form').addEventListener('submit', submitAuth); $('#auth-switch').addEventListener('click', () => { const signup = $('#auth-mode').value !== 'signup'; $('#auth-mode').value = signup ? 'signup' : 'signin'; $('#auth-submit').textContent = signup ? 'Create account' : 'Sign in'; $('#auth-switch').textContent = signup ? 'Already registered? Sign in' : 'New player? Register'; showAuthMessage(''); }); $('#sign-out').addEventListener('click', () => db.auth.signOut());
document.querySelectorAll('.tab').forEach((tab) => tab.addEventListener('click', () => { if (tab.hidden) return; document.querySelectorAll('.tab,.view').forEach((el) => el.classList.remove('is-active')); tab.classList.add('is-active'); $(`#${tab.dataset.view}`).classList.add('is-active'); }));
$('#export-data').addEventListener('click', () => { const blob = new Blob([JSON.stringify(state, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'social-sports-backup.json'; link.click(); URL.revokeObjectURL(link.href); });
db.auth.onAuthStateChange((event) => { if (event === 'SIGNED_OUT') { state.profile = null; $('#auth-dialog').showModal(); } if (event === 'SIGNED_IN') setTimeout(startApp, 0); }); ['players', 'games', 'grounds', 'registrations', 'club_settings', 'profiles'].forEach((table) => db.channel(`shared-${table}`).on('postgres_changes', { event: '*', schema: 'public', table }, () => state.profile && loadData()).subscribe()); startApp();
